name: Unlock-NetEaseMusic

on:
  schedule:
    - cron: "37 */8 * * *" # Runs every 8 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install specific Chrome version 134.0.6998
        run: |
          echo "Installing specific Google Chrome version 134.0.6998..."
          choco install googlechrome --version 134.0.6998 -y
          echo "✅ Google Chrome 134.0.6998 installed successfully."

      - name: Install specific Chromedriver version 134.0.6998.88
        run: |
          echo "Installing specific Chromedriver version 134.0.6998.88..."
          choco install chromedriver --version 134.0.6998.88 -y --force
          echo "✅ Chromedriver 134.0.6998.88 installed successfully."

      - name: Debug Chrome and Chromedriver
        shell: pwsh
        run: |
          echo "Checking Chrome version..."
          if (Test-Path "C:\Program Files\Google\Chrome\Application\chrome.exe") {
              & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version
          } else {
              echo "❌ Chrome not found!"
          }

          echo "Checking Chromedriver version..."
          if (Get-Command chromedriver -ErrorAction SilentlyContinue) {
              chromedriver --version
          } else {
              echo "❌ Chromedriver not found!"
          }

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unlock script
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PYTHONIOENCODING: utf-8
          PYTHONLEGACYWINDOWSSTDIO: utf-8
        run: python auto_login.py
